AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Graph RAG App 2: Vector Splitter & Graph Extractor.
  Listens to JSONL output from App 1, splits vectors, and extracts Graph data.

Parameters:
  # This bucket will be CREATED by this stack to allow auto-triggering
  GraphInputBucketName:
    Type: String
    Default: my-graph-input-bucket-2025
    Description: >
      The bucket where App 1 should drop its JSONL files. 
      (App 2 listens to this bucket).

  # The final destination for the split files
  FinalOutputBucketName:
    Type: String
    Default: my-graph-final-artifacts-2025
    Description: Existing bucket to store the final Split Vectors (A) and Graph Data (B).

Globals:
  Function:
    Timeout: 900 # Increased to 15 mins (LLM latency buffer)
    MemorySize: 2048 # 2GB RAM (Sufficient for streaming)
    LoggingConfig:
      LogFormat: JSON

Resources:
  # 1. The Trigger Bucket (App 2 owns this to enable auto-triggers)
  GraphInputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref GraphInputBucketName

  # 2. The Processor Function
  GraphProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          FINAL_OUTPUT_BUCKET: !Ref FinalOutputBucketName
          POWERTOOLS_SERVICE_NAME: "graph-processor"
      Policies:
        # Read from Input
        - S3ReadPolicy:
            BucketName: !Ref GraphInputBucketName
        # Write to Output
        - S3WritePolicy:
            BucketName: !Ref FinalOutputBucketName
        # Bedrock Access
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*" 
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref GraphInputBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jsonl

    Metadata:
      DockerTag: python3.12-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  GraphProcessorFunction:
    Description: "Graph Processor Lambda Function ARN"
    Value: !GetAtt GraphProcessorFunction.Arn
  GraphInputBucket:
    Description: "COPY THIS -> Use this as the 'OutputBucketName' for App 1"
    Value: !Ref GraphInputBucket