# Use the official AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.9

# Copy requirements and install
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the app code
COPY src/app.py .

# Set the CMD to your handler (filename.function_name)
CMD ["app.lambda_handler"]