AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Jsonl Splitter (v2) and Bedrock Graph Extractor

Parameters:
  InputBucketName:
    Type: String
    Description: "New bucket for uploads (e.g. quad-input-123)"
  OutputBucketName:
    Type: String
    Description: "Existing bucket for intermediate results"
  GraphBucketName:
    Type: String
    Description: "NEW bucket for final Graph Data (e.g. quad-graph-data)"
  ModelId:
    Type: String
    Default: "amazon.titan-text-express-v1"
    Description: "AWS Bedrock Model ID"

Globals:
  Function:
    MemorySize: 512
    Architectures: [x86_64]
    Environment:
      Variables:
        OUTPUT_BUCKET: !Ref OutputBucketName
        GRAPH_BUCKET: !Ref GraphBucketName
        LLM_MODEL: !Ref ModelId

Resources:
  # ---------------------------------------------------------
  # Function 1: Splitter (Using V2 Code)
  # ---------------------------------------------------------
  SplitterFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 60
      Policies:
        - S3CrudPolicy:
            BucketName: "*"
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jsonl
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./splitter_v2
      DockerTag: splitter-v2

  # ---------------------------------------------------------
  # Function 2: Graph Extractor (Bedrock)
  # ---------------------------------------------------------
  GraphFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
      Policies:
        # Permission to access ALL buckets (Existing & New)
        - S3CrudPolicy:
            BucketName: "*"
        # Permission to use Bedrock
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      # NOTE: S3 Trigger Removed to prevent deployment error.
      # You must add the trigger manually in the AWS Console.
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./graph_extractor
      DockerTag: graph-v1

  # ---------------------------------------------------------
  # Buckets
  # ---------------------------------------------------------
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName

  GraphDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref GraphBucketName

Outputs:
  SplitterArn:
    Value: !GetAtt SplitterFunction.Arn
  GraphFunctionArn:
    Description: "Use this ARN to set up the S3 Trigger manually"
    Value: !GetAtt GraphFunction.Arn
  GraphBucket:
    Value: !Ref GraphDataBucket