AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Docling Multi-Format RAG Pre-processor (Ingest Only)

Parameters:
  InputBucketName:
    Type: String
    Default: my-docling-input-data-2025
    Description: Name of the existing S3 bucket for input files
  OutputBucketName:
    Type: String
    Default: my-docling-output-artifacts-2025
    Description: Name of the existing S3 bucket for output artifacts

Globals:
  Function:
    Timeout: 900 # Increased to 15 mins (Max) for large PDF/OCR jobs
    MemorySize: 4096 # Increased to 4GB for ML model inference
    Environment:
      Variables:
        HF_HOME: /tmp/hf_home
        TORCH_HOME: /tmp/torch_home

Resources:
  # 3. Lambda Function (Container Image based)
  DoclingIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      # Define S3 permissions (Bedrock removed as embeddings are now in App 2)
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref InputBucketName
        - S3WritePolicy:
            BucketName: !Ref OutputBucketName
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucketName
          USE_VLM: "false"
          PRETTY_JSON: "true"
      # NOTE: Configure S3 Event Notification manually in AWS Console
      # Bucket -> Properties -> Event notifications -> Create event notification -> Select Lambda Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

Outputs:
  DoclingIngestFunctionArn:
    Description: "Docling Ingest Lambda Function ARN"
    Value: !GetAtt DoclingIngestFunction.Arn
  InputBucketName:
    Description: "Upload files here"
    Value: !Ref InputBucketName
  OutputBucketName:
    Description: "Retrieve results here"
    Value: !Ref OutputBucketName